const vscode=require('vscode');
const path=require('path');
class ReviewTreeProvider{
 constructor(reviewState,isReviewed){this.reviewState=reviewState;this.isReviewed=isReviewed;this._onDidChangeTreeData=new vscode.EventEmitter();this.onDidChangeTreeData=this._onDidChangeTreeData.event;}
 refresh(){this._onDidChangeTreeData.fire();}
 getTreeItem(el){
  if(el.kind==='summary')return el.item;
  if(el.kind==='folder'){const t=new vscode.TreeItem(el.name,vscode.TreeItemCollapsibleState.Expanded);t.iconPath=new vscode.ThemeIcon('folder');t.description=`${el.reviewed}/${el.total}`;return t;}
  if(el.kind==='pendingFolder'){const t=new vscode.TreeItem('Pending Review',vscode.TreeItemCollapsibleState.Expanded);t.iconPath=new vscode.ThemeIcon('edit');t.description=`${el.children.length} unpublished`;return t;}
  if(el.kind==='pendingComment'){const t=new vscode.TreeItem(oneLine(el.note.body),vscode.TreeItemCollapsibleState.None);t.description=`You · Pending · ${el.note.path}:${el.note.newLine||el.note.oldLine||''}`;t.iconPath=new vscode.ThemeIcon('comment-draft');t.tooltip=`Pending · not published\n${el.note.path}:${el.note.newLine||el.note.oldLine||''}\n${el.note.body}`;t.command={command:'gitlabWorkbench.openPendingReviewComment',title:'Open pending review comment',arguments:[el.note]};t.contextValue='pendingReviewComment';return t;}
  if(el.kind==='generalFolder'){const t=new vscode.TreeItem('Merge Request Discussion',vscode.TreeItemCollapsibleState.Expanded);t.iconPath=new vscode.ThemeIcon('comment-discussion');t.description=`${el.children.length} thread${el.children.length===1?'':'s'}`;t.contextValue='generalDiscussionFolder';return t;}
  if(el.kind==='comment'){const first=el.discussion.notes[0];const t=new vscode.TreeItem(oneLine(first.body),vscode.TreeItemCollapsibleState.None);const meta=[first.author];if(el.discussion.path&&!el.discussion.resolved)meta.push(`Line ${el.discussion.line}`);else if(el.discussion.resolved)meta.push('Resolved');else if(el.discussion.resolvable)meta.push('Unresolved');else meta.push('General');t.description=meta.filter(Boolean).join(' · ');t.iconPath=new vscode.ThemeIcon(el.discussion.resolved?'pass':'comment-discussion');const location=el.discussion.path?`\n${el.discussion.path}${el.discussion.line?`:${el.discussion.line}`:''}`:'';t.tooltip=`${el.discussion.resolved?'Resolved thread':'Review thread'}${location}\n\n${el.discussion.notes.map(n=>`${n.author}: ${n.body}`).join('\n\n')}`;t.command=el.discussion.path?{command:'gitlabWorkbench.openDiscussion',title:'Open comment',arguments:[el.discussion]}:undefined;t.contextValue=el.discussion.resolvable?(el.discussion.resolved?'reviewDiscussionResolved':'reviewDiscussion'):'reviewGeneralDiscussion';return t;}
  const active=this.reviewState.index===el.index;const reviewed=this.isReviewed(el.mr,el.file[0]);const discussions=(this.reviewState.discussions||[]).filter(d=>d.path===el.file[0]);const unresolved=discussions.filter(d=>!d.resolved).length;const name=path.basename(el.file[0]);
  const t=new vscode.TreeItem(name,discussions.length?vscode.TreeItemCollapsibleState.Expanded:vscode.TreeItemCollapsibleState.None);const fileMeta=[`+${el.file[1]} −${el.file[2]}`];if(unresolved)fileMeta.push(`💬 ${unresolved}`);if(active)fileMeta.push('Current');t.description=fileMeta.join('  ·  ');t.tooltip=`${el.file[0]}\n${reviewed?'Reviewed':'Not reviewed'}\n+${el.file[1]} -${el.file[2]}${unresolved?`\n${unresolved} unresolved review comment(s)`:''}`;t.iconPath=new vscode.ThemeIcon(reviewed?'pass':active?'eye':'circle-outline');t.contextValue=reviewed?'reviewFileReviewed':'reviewFile';t.command={command:'gitlabWorkbench.openReviewFile',title:'Open changed file',arguments:[el.index]};t.discussions=discussions;return t;
 }
 getChildren(el){const mr=this.reviewState.mr;if(!mr)return [];
  if(!el){const files=mr.files||[],done=files.filter(f=>this.isReviewed(mr,f[0])).length,unresolved=(this.reviewState.discussions||[]).filter(d=>!d.resolved).length,pending=this.reviewState.pending||[];const s=new vscode.TreeItem(`Review !${mr.iid} · ${done}/${files.length}`,vscode.TreeItemCollapsibleState.None);s.description=`${mr.repo}${pending.length?` · ✎ ${pending.length} pending`:''}${unresolved?` · 💬 ${unresolved} unresolved`:''}`;s.iconPath=new vscode.ThemeIcon(unresolved?'comment-discussion':done===files.length?'verified':'git-pull-request');s.contextValue='reviewSummary';const all=this.reviewState.discussions||[];const visible=this.reviewState.hideResolved?all.filter(d=>!d.resolved):all;const general=visible.filter(d=>!d.path).map(d=>({kind:'comment',discussion:d}));const generalNode=general.length?[{kind:'generalFolder',children:general}]:[];const pendingNode=pending.length?[{kind:'pendingFolder',children:pending.map(note=>({kind:'pendingComment',note}))}]:[];return [{kind:'summary',item:s},...pendingNode,...generalNode,...buildFolders(files,mr,this.isReviewed,visible)];}
  if(el.kind==='folder'||el.kind==='generalFolder'||el.kind==='pendingFolder')return el.children;if(el.kind==='file')return (el.discussions||[]).map(d=>({kind:'comment',discussion:d}));return [];
 }
}
function buildFolders(files,mr,isReviewed,discussions){const roots=new Map();files.forEach((f,index)=>{const parts=f[0].split('/');const dir=parts.length>1?parts.slice(0,-1).join('/'):'(root)';if(!roots.has(dir))roots.set(dir,[]);roots.get(dir).push({kind:'file',file:f,index,mr,discussions:discussions.filter(d=>d.path===f[0])});});return [...roots.entries()].map(([name,children])=>({kind:'folder',name,children,total:children.length,reviewed:children.filter(x=>isReviewed(mr,x.file[0])).length}));}
function oneLine(s){s=String(s||'').replace(/\s+/g,' ').trim();return s.length>55?s.slice(0,52)+'…':s;}
module.exports={ReviewTreeProvider};
